export const WORDS = [
  {
    "word": "MORTGAGE",
    "hint1": "I am a specific type of loan used to buy a house.",
    "hint2": "If you stop paying me, the bank can take your home.",
    "hint3": "My name literally translates to \"Death Pledge.\"",
    "definition": "A loan specifically used to purchase a home or real estate, secured by the property itself."
  },
  {
    "word": "DIVIDEND",
    "hint1": "I am a \"thank you\" payment from a company to its owners.",
    "hint2": "I am usually paid quarterly in cash.",
    "hint3": "Tech companies like Google and Amazon rarely pay me.",
    "definition": "A portion of a company's profit paid out to shareholders, usually on a quarterly basis."
  },
  {
    "word": "INFLATION",
    "hint1": "I am the reason a candy bar costs more today than 10 years ago.",
    "hint2": "Central banks try to keep me around 2%.",
    "hint3": "When I get too high (Hyper-), money becomes worthless.",
    "definition": "The rate at which the general level of prices for goods and services is rising."
  },
  {
    "word": "BUDGET",
    "hint1": "I am a plan that tells your money where to go.",
    "hint2": "Governments and households both need me to avoid overspending.",
    "hint3": "I balance your \"Income\" against your \"Expenses.\"",
    "definition": "An estimation of revenue and expenses over a specified future period of time."
  },
  {
    "word": "ASSET",
    "hint1": "I am anything you own that has cash value.",
    "hint2": "A house, a car, and cash are all examples of me.",
    "hint3": "I am the opposite of a \"Liability.\"",
    "definition": "A resource with economic value that an individual or corporation owns with the expectation of future benefit."
  },
  {
    "word": "LIQUIDITY",
    "hint1": "I measure how fast you can turn something into cash.",
    "hint2": "Real estate has low [me]; Cash has high [me].",
    "hint3": "If a business lacks me, it might fail even if it's profitable.",
    "definition": "The ease with which an asset or security can be converted into ready cash without affecting its market price."
  },
  {
    "word": "SALARY",
    "hint1": "I am the fixed amount you get paid for your job.",
    "hint2": "Unlike hourly wages, I don't usually go up if you work 5 extra minutes.",
    "hint3": "My name comes from the Latin word for \"Salt.\"",
    "definition": "A fixed regular payment, typically paid on a monthly or biweekly basis but expressed as an annual sum."
  },
  {
    "word": "INTEREST",
    "hint1": "I am the cost of \"renting\" someone else's money.",
    "hint2": "I can work for you (savings) or against you (loans).",
    "hint3": "Einstein called my \"compound\" version the 8th wonder of the world.",
    "definition": "The charge for the privilege of borrowing money, typically expressed as an annual percentage rate."
  },
  {
    "word": "REVENUE",
    "hint1": "I am the total money a business brings in before paying bills.",
    "hint2": "I am often called the \"Top Line\" of a financial statement.",
    "hint3": "Sales multiplied by Price equals Me.",
    "definition": "The total amount of income generated by the sale of goods or services related to the company's primary operations."
  },
  {
    "word": "BULL",
    "hint1": "I am an animal that attacks by thrusting horns upward.",
    "hint2": "I represent optimism and a rising stock market.",
    "hint3": "A statue of me stands famously near Wall Street.",
    "definition": "An investor who expects prices to rise, or a market condition where prices are rising."
  },
  {
    "word": "BEAR",
    "hint1": "I am an animal that attacks by swiping paws downward.",
    "hint2": "I represent pessimism and a crashing market.",
    "hint3": "I am the scary opposite of a Bull.",
    "definition": "An investor who expects prices to fall, or a market condition where prices are falling."
  },
  {
    "word": "CAPITAL",
    "hint1": "I am the money needed to start a business.",
    "hint2": "Venture [Me] firms invest in startups.",
    "hint3": "I am also the name for the city where a government is located.",
    "definition": "Wealth in the form of money or other assets owned by a person or organization for starting or investing in a business."
  },
  {
    "word": "AUDIT",
    "hint1": "I am a scary check-up for your financial records.",
    "hint2": "The IRS performs me to catch tax cheats.",
    "hint3": "My name comes from the Latin word \"to hear.\"",
    "definition": "An official inspection of an individual's or organization's accounts, typically by an independent body."
  },
  {
    "word": "CURRENCY",
    "hint1": "I am the physical or digital money used in a country.",
    "hint2": "The Dollar, Euro, and Yen are famous examples of me.",
    "hint3": "Crypto[me] is a new digital form of me.",
    "definition": "A system of money in general use in a particular country."
  },
  {
    "word": "LIABILITY",
    "hint1": "I am anything you owe to someone else.",
    "hint2": "Loans, mortgages, and unpaid bills are all types of me.",
    "hint3": "Assets minus [Me] equals Equity.",
    "definition": "A thing for which someone is responsible, especially a debt or financial obligation."
  },
  {
    "word": "PREMIUM",
    "hint1": "I am the monthly bill you pay for insurance.",
    "hint2": "I can also mean \"high quality\" or \"extra price.\"",
    "hint3": "If you are a risky driver, I get more expensive.",
    "definition": "An amount to be paid for an insurance policy."
  },
  {
    "word": "PORTFOLIO",
    "hint1": "I am the collection of all your stocks and bonds.",
    "hint2": "You should \"diversify\" me to be safe.",
    "hint3": "Artists have one for art; investors have one for money.",
    "definition": "A range of investments held by a person or organization."
  },
  {
    "word": "LEDGER",
    "hint1": "I am the master book where all transactions are recorded.",
    "hint2": "Blockchain is a \"Distributed\" type of me.",
    "hint3": "Before computers, I was a heavy physical book.",
    "definition": "A book or other collection of financial accounts of a particular type."
  },
  {
    "word": "CREDIT",
    "hint1": "I let you buy now and pay later.",
    "hint2": "My \"Score\" determines if you can get a loan.",
    "hint3": "\"Plastic money\" cards are named after me.",
    "definition": "The ability of a customer to obtain goods or services before payment, based on the trust that payment will be made in the future."
  },
  {
    "word": "BROKER",
    "hint1": "I am the middleman between a buyer and a seller.",
    "hint2": "Real estate agents and stock trading apps act as me.",
    "hint3": "I \"break\" a deal into a finished contract.",
    "definition": "An individual or firm that charges a fee or commission for executing buy and sell orders submitted by an investor."
  },
  {
    "word": "RECESSION",
    "hint1": "I happen when the economy shrinks for 6 months.",
    "hint2": "I am the scary cousin of a Depression.",
    "hint3": "During me, unemployment usually goes up.",
    "definition": "A period of temporary economic decline during which trade and industrial activity are reduced."
  },
  {
    "word": "SAVINGS",
    "hint1": "I am the money you don't spend today.",
    "hint2": "You keep me in a piggy bank or a bank account.",
    "hint3": "Rainy day funds are made of me.",
    "definition": "The money one has saved, especially through a bank or official scheme."
  },
  {
    "word": "TREASURY",
    "hint1": "I am the government department that prints money.",
    "hint2": "[Me] Bonds are loans to the US Government.",
    "hint3": "My signature is on every dollar bill.",
    "definition": "A government department responsible for managing public finance and currency."
  },
  {
    "word": "PROFIT",
    "hint1": "I am what's left after you pay all expenses.",
    "hint2": "Revenue minus Cost equals Me.",
    "hint3": "Businesses exist to make me.",
    "definition": "A financial gain, especially the difference between the amount earned and the amount spent in buying, operating, or producing something."
  },
  {
    "word": "PENSION",
    "hint1": "I am a paycheck you get after you retire.",
    "hint2": "Teachers and government workers often get me.",
    "hint3": "I replace your salary when you get old.",
    "definition": "A regular payment made during a person's retirement from an investment fund."
  },
  {
    "word": "OPTION",
    "hint1": "I give you the \"choice\" to buy a stock later.",
    "hint2": "Employees often get stock [me]s as a bonus.",
    "hint3": "I am risky but can lead to huge gains.",
    "definition": "A contract which gives the buyer the right, but not the obligation, to buy or sell an asset at a set price."
  },
  {
    "word": "UNICORN",
    "hint1": "I am a mythical creature with one horn.",
    "hint2": "In finance, I am a startup worth $1 billion.",
    "hint3": "Uber and Airbnb were me before they went public.",
    "definition": "A privately held startup company valued at over $1 billion."
  },
  {
    "word": "BONDS",
    "hint1": "I am an IOU from a government or company.",
    "hint2": "I am safer than stocks but usually pay less.",
    "hint3": "James [Me] is a spy; Treasury [Me] is an investment.",
    "definition": "Fixed income instruments that represent a loan made by an investor to a borrower."
  },
  {
    "word": "WALLET",
    "hint1": "I hold your cash and IDs.",
    "hint2": "In crypto, I am a digital app to store keys.",
    "hint3": "Losing me is a nightmare for anyone.",
    "definition": "A pocket-sized, flat, folding case for holding money, or a digital app for holding crypto keys."
  },
  {
    "word": "BARTER",
    "hint1": "I am how people traded before money existed.",
    "hint2": "\"I'll give you a chicken for your shoes\" is an example of me.",
    "hint3": "Kids do this with lunch items at school.",
    "definition": "The action or system of exchanging goods or services without using money."
  },
  {
    "word": "ARBITRAGE",
    "hint1": "Buying low in one place and selling high in another instantly.",
    "hint2": "It is often considered \"risk-free\" profit.",
    "hint3": "High-speed computers do this in milliseconds.",
    "definition": "The simultaneous buying and selling of securities in different markets to profit from price differences."
  },
  {
    "word": "BANKRUPTCY",
    "hint1": "The legal word for \"going broke.\"",
    "hint2": "You declare this when you can't pay your debts.",
    "hint3": "The name comes from Italian for \"broken bench.\"",
    "definition": "A legal proceeding involving a person or business that is unable to repay their outstanding debts."
  },
  {
    "word": "COLLATERAL",
    "hint1": "The asset you promise to give up if you don't pay.",
    "hint2": "For a mortgage, the house itself is this.",
    "hint3": "Pawn shops keep your item as this.",
    "definition": "An asset pledged by a borrower to secure a loan, which is forfeited if the loan is not repaid."
  },
  {
    "word": "DERIVATIVE",
    "hint1": "My value depends on something else.",
    "hint2": "Options and Futures are types of me.",
    "hint3": "Warren Buffett called me a \"weapon of mass destruction.\"",
    "definition": "A financial security with a value that is reliant upon or derived from an underlying asset."
  },
  {
    "word": "FIDUCIARY",
    "hint1": "A professional legally forced to put you before themselves.",
    "hint2": "Not all financial advisors are this; some are salespeople.",
    "hint3": "Trustees and guardians are examples of me.",
    "definition": "A person or organization that acts on behalf of another and is legally bound to act in their best interest."
  },
  {
    "word": "INSOLVENCY",
    "hint1": "The state of having empty pockets when bills are due.",
    "hint2": "This is the step before declaring bankruptcy.",
    "hint3": "You can be profitable but still suffer from this (no cash).",
    "definition": "The state of being unable to pay debts as they fall due."
  },
  {
    "word": "ARBITRAGE",
    "hint1": "Buying low in one place and selling high in another instantly.",
    "hint2": "It is often considered \"risk-free\" profit.",
    "hint3": "High-speed computers do this in milliseconds.",
    "definition": "The simultaneous buying and selling of securities in different markets to profit from price differences."
  },
  {
    "word": "FIDUCIARY",
    "hint1": "A professional legally forced to put you before themselves.",
    "hint2": "Not all financial advisors are this; some are salespeople.",
    "hint3": "Trustees and guardians are examples of me.",
    "definition": "A person or organization that acts on behalf of another and is legally bound to act in their best interest."
  },
  {
    "word": "ACCRUAL",
    "hint1": "Recording money when earned, not when paid.",
    "hint2": "The opposite of \"Cash Basis\" accounting.",
    "hint3": "Large companies must use this method.",
    "definition": "An accounting method where revenue or expenses are recorded when they occur, not when cash changes hands."
  },
  {
    "word": "DERIVATIVE",
    "hint1": "My value depends on something else.",
    "hint2": "Options and Futures are types of me.",
    "hint3": "Warren Buffett called me a \"weapon of mass destruction.\"",
    "definition": "A financial security with a value that is reliant upon or derived from an underlying asset."
  },
  {
    "word": "COLLATERAL",
    "hint1": "The asset you promise to give up if you don't pay.",
    "hint2": "For a mortgage, the house itself is this.",
    "hint3": "Pawn shops keep your item as this.",
    "definition": "An asset pledged by a borrower to secure a loan, which is forfeited if the loan is not repaid."
  },
  {
    "word": "ANNUITY",
    "hint1": "You buy me to get a steady paycheck in retirement.",
    "hint2": "I am the reverse of life insurance; I pay you while you live.",
    "hint3": "Roman soldiers were paid \"annua,\" the origin of my name.",
    "definition": "A financial product sold by insurance companies that provides a fixed stream of payments to an individual."
  },
  {
    "word": "DEBENTURE",
    "hint1": "I am a bond backed only by the company's reputation.",
    "hint2": "I am riskier than a secured bond because I have no collateral.",
    "hint3": "Big reliable companies issue me to raise money.",
    "definition": "A type of long-term bond that is not secured by any collateral."
  },
  {
    "word": "GOODWILL",
    "hint1": "I am the value of a brand's name.",
    "hint2": "You can't touch me, but I'm worth billions to Coca-Cola.",
    "hint3": "I appear on the balance sheet after a company is bought.",
    "definition": "An intangible asset representing non-physical value like brand reputation or customer loyalty."
  },
  {
    "word": "COVENANT",
    "hint1": "I am a strict rule written into a loan contract.",
    "hint2": "If you break me, the bank can demand all money back.",
    "hint3": "I protect the lender from the borrower taking big risks.",
    "definition": "A condition or clause in a loan agreement that requires the borrower to fulfill certain obligations."
  },
  {
    "word": "SOLVENCY",
    "hint1": "I measure if a company can survive in the long run.",
    "hint2": "If you lack me, you will eventually go out of business.",
    "hint3": "I am different from liquidity (which is short-term).",
    "definition": "The ability of a company to meet its long-term debts and financial obligations."
  },
  {
    "word": "PROSPECTUS",
    "hint1": "The thick legal book given to investors before an IPO.",
    "hint2": "I list all the scary \"Risk Factors\" of the stock.",
    "hint3": "You should read me before investing, but few do.",
    "definition": "A formal legal document detailing an investment offering to the public."
  },
  {
    "word": "SYNERGY",
    "hint1": "The magic math where 1 + 1 = 3.",
    "hint2": "CEOs love to say this word when merging companies.",
    "hint3": "I mean working better together than apart.",
    "definition": "The concept that the value and performance of two companies combined will be greater than the sum of the separate individual parts."
  },
  {
    "word": "TRANCHE",
    "hint1": "I am a French word for \"slice.\"",
    "hint2": "Bankers slice up mortgage bundles into me.",
    "hint3": "Some of me are safe (AAA), some are toxic (Junk).",
    "definition": "A portion of a pool of securities, usually differentiated by risk or maturity."
  },
  {
    "word": "HEDGING",
    "hint1": "I am like buying insurance for your investments.",
    "hint2": "Farmers do this to lock in crop prices.",
    "hint3": "I limit your losses if the market goes against you.",
    "definition": "A strategy used to offset the risk of any adverse price movements."
  },
  {
    "word": "ACTUARY",
    "hint1": "I use math to calculate when people will die (for insurance).",
    "hint2": "I determine how much your insurance premium costs.",
    "hint3": "I am a high-paying job for people who love statistics.",
    "definition": "A professional who analyzes statistics to calculate insurance risks and premiums."
  },
  {
    "word": "VARIANCE",
    "hint1": "I measure how much data spreads out from the average.",
    "hint2": "In finance, high [me] means high volatility/risk.",
    "hint3": "I am the square of standard deviation.",
    "definition": "A statistical measurement of how far a set of numbers is spread out from their average value."
  },
  {
    "word": "ESCROW",
    "hint1": "I hold the money in the middle until the deal is done.",
    "hint2": "When buying a house, your deposit sits in me.",
    "hint3": "I protect both the buyer and the seller from fraud.",
    "definition": "A legal arrangement where a third party holds money or assets until a condition is met."
  },
  {
    "word": "YIELD",
    "hint1": "I am the % return you get from a bond or dividend.",
    "hint2": "If the bond price goes down, I usually go up.",
    "hint3": "Farmers harvest crops; investors harvest me.",
    "definition": "The income return on an investment, usually expressed as an annual percentage."
  },
  {
    "word": "VALUATION",
    "hint1": "The process of figuring out what a company is worth.",
    "hint2": "Shark Tank judges argue about me constantly.",
    "hint3": "For startups, I am often based on future hopes, not current cash.",
    "definition": "The process of determining the current worth of an asset or a company."
  },
  {
    "word": "LIEN",
    "hint1": "A legal claim on your property because you owe money.",
    "hint2": "A mechanic can put me on your car if you don't pay.",
    "hint3": "I stick to the property until the debt is cleared.",
    "definition": "A legal right to keep possession of property belonging to another person until a debt is paid."
  },
  {
    "word": "VOLATILITY",
    "hint1": "I measure how wildly a stock price swings up and down.",
    "hint2": "Crypto is famous for having high [me].",
    "hint3": "The \"VIX\" index measures me (often called the Fear Index).",
    "definition": "A statistical measure of the dispersion of returns for a given security or market index."
  },
  {
    "word": "CORRECTION",
    "hint1": "I am a market drop of 10% to 20%.",
    "hint2": "I am considered \"healthy\" to cool down an overheated market.",
    "hint3": "I am smaller than a Crash but bigger than a dip.",
    "definition": "A decline of 10% or more in the price of a security or market from its recent peak."
  },
  {
    "word": "DEFICIT",
    "hint1": "I happen when you spend more than you earn.",
    "hint2": "Governments run me almost every year.",
    "hint3": "When I accumulate over years, I become \"Debt.\"",
    "definition": "The amount by which spending exceeds revenue over a particular period of time."
  },
  {
    "word": "INDENTURE",
    "hint1": "I am the contract that governs a bond.",
    "hint2": "I list the interest rate, maturity date, and rules.",
    "hint3": "Historically, my paper edges were cut (indented) for proof.",
    "definition": "The formal legal contract between a bond issuer and the bondholders."
  },
  {
    "word": "SENTIMENT",
    "hint1": "I measure the \"mood\" of the market.",
    "hint2": "I can be \"Bullish\" (happy) or \"Bearish\" (sad).",
    "hint3": "\"Fear and Greed\" are my two main extremes.",
    "definition": "The overall attitude of investors toward a particular security or financial market."
  },
  {
    "word": "LIQUIDATE",
    "hint1": "I mean selling everything to get cash.",
    "hint2": "\"Everything Must Go!\" usually accompanies me.",
    "hint3": "Stores do this when they go out of business.",
    "definition": "To close a business and sell its assets to pay off debts."
  },
  {
    "word": "AMORTIZE",
    "hint1": "The process of killing a loan through regular payments.",
    "hint2": "Each payment covers some interest and some principal.",
    "hint3": "My root word means \"to death.\"",
    "definition": "To gradually write off the initial cost of an asset or reduce a debt with regular payments."
  },
  {
    "word": "CEILING",
    "hint1": "I am the maximum limit on a price or debt.",
    "hint2": "The US Government fights over the \"Debt [Me]\" often.",
    "hint3": "Rent control is a type of price [me].",
    "definition": "A government-imposed upper limit on the price of a product, service, or interest rate."
  },
  {
    "word": "HAWKISH",
    "hint1": "I am a bird that represents aggressive high interest rates.",
    "hint2": "I want to fight inflation, even if it hurts growth.",
    "hint3": "I am the opposite of a \"Dove.\"",
    "definition": "A policy stance that favors higher interest rates to keep inflation in check."
  },
  {
    "word": "VESTING",
    "hint1": "The waiting period before you get your company stock.",
    "hint2": "\"Golden Handcuffs\" use me to make you stay at a job.",
    "hint3": "If you quit early, you lose the shares that haven't finished this.",
    "definition": "The process by which an employee earns the right to receive stock options or benefits over time."
  }
]